export type GrammarPhrase = {
  id: string;
  it: string;
  ru: string;
  tense: "presente" | "passato" | "imperfetto" | "futuro";
  pronoun: string;
};

export type WordOfDay = {
  day: number;
  verb: string;
  translation: string;
  phrases: GrammarPhrase[];
};

export const grammarDays: WordOfDay[] = [
  {
    day: 1,
    verb: "lavorare",
    translation: "работать",
    phrases: [
      // Presente
      { id: "lav-pre-1", tense: "presente", pronoun: "io", it: "Lavoro da casa ogni giorno.", ru: "Я работаю из дома каждый день." },
      { id: "lav-pre-2", tense: "presente", pronoun: "tu", it: "Lavori troppo ultimamente.", ru: "В последнее время ты слишком много работаешь." },
      { id: "lav-pre-3", tense: "presente", pronoun: "lui", it: "Lui lavora in centro.", ru: "Он работает в центре." },
      { id: "lav-pre-4", tense: "presente", pronoun: "lei", it: "Lei lavora con i bambini.", ru: "Она работает с детьми." },
      { id: "lav-pre-5", tense: "presente", pronoun: "noi", it: "Noi lavoriamo insieme.", ru: "Мы работаем вместе." },
      { id: "lav-pre-6", tense: "presente", pronoun: "voi", it: "Voi lavorate bene.", ru: "Вы хорошо работаете." },
      { id: "lav-pre-7", tense: "presente", pronoun: "loro", it: "Loro lavorano tutto il giorno.", ru: "Они работают весь день." },
      { id: "lav-pre-8", tense: "presente", pronoun: "io", it: "Lavoro con l'intelligenza artificiale.", ru: "Я работаю с искусственным интеллектом." },
      { id: "lav-pre-9", tense: "presente", pronoun: "io", it: "Non lavoro il weekend.", ru: "Я не работаю в выходные." },
      { id: "lav-pre-10", tense: "presente", pronoun: "tu", it: "A che ora lavori domani?", ru: "В котором часу ты работаешь завтра?" },
      // Passato
      { id: "lav-pas-1", tense: "passato", pronoun: "io", it: "Ieri ho lavorato molto.", ru: "Вчера я много работал." },
      { id: "lav-pas-2", tense: "passato", pronoun: "tu", it: "Hai lavorato oggi?", ru: "Ты работал сегодня?" },
      { id: "lav-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha lavorato tutta la notte.", ru: "Он работал всю ночь." },
      { id: "lav-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha lavorato da casa.", ru: "Она работала из дома." },
      { id: "lav-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo lavorato insieme ieri.", ru: "Вчера мы работали вместе." },
      { id: "lav-pas-6", tense: "passato", pronoun: "voi", it: "Avete lavorato bene oggi.", ru: "Сегодня вы хорошо работали." },
      { id: "lav-pas-7", tense: "passato", pronoun: "loro", it: "Hanno lavorato fino a tardi.", ru: "Они работали допоздна." },
      { id: "lav-pas-8", tense: "passato", pronoun: "io", it: "Ho lavorato per dieci ore.", ru: "Я работал десять часов." },
      { id: "lav-pas-9", tense: "passato", pronoun: "io", it: "Non ho lavorato ieri sera.", ru: "Вчера вечером я не работал." },
      { id: "lav-pas-10", tense: "passato", pronoun: "tu", it: "Quanto hai lavorato questa settimana?", ru: "Сколько ты работал на этой неделе?" },
      // Imperfetto
      { id: "lav-imp-1", tense: "imperfetto", pronoun: "io", it: "Prima lavoravo in ufficio.", ru: "Раньше я работал в офисе." },
      { id: "lav-imp-2", tense: "imperfetto", pronoun: "tu", it: "Lavoravi molto da giovane.", ru: "В молодости ты много работал." },
      { id: "lav-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui lavorava in banca.", ru: "Он работал в банке." },
      { id: "lav-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei lavorava come insegnante.", ru: "Она работала учительницей." },
      { id: "lav-imp-5", tense: "imperfetto", pronoun: "noi", it: "Lavoravamo dodici ore al giorno.", ru: "Мы работали двенадцать часов в день." },
      { id: "lav-imp-6", tense: "imperfetto", pronoun: "voi", it: "Lavoravate sempre insieme.", ru: "Вы всегда работали вместе." },
      { id: "lav-imp-7", tense: "imperfetto", pronoun: "loro", it: "Lavoravano senza pause.", ru: "Они работали без перерывов." },
      { id: "lav-imp-8", tense: "imperfetto", pronoun: "io", it: "Lavoravo anche la domenica.", ru: "Я работал даже в воскресенье." },
      { id: "lav-imp-9", tense: "imperfetto", pronoun: "io", it: "Non lavoravo mai di notte.", ru: "Я никогда не работал ночью." },
      { id: "lav-imp-10", tense: "imperfetto", pronoun: "tu", it: "Dove lavoravi prima?", ru: "Где ты раньше работал?" },
      // Futuro
      { id: "lav-fut-1", tense: "futuro", pronoun: "io", it: "Domani lavorerò da casa.", ru: "Завтра я буду работать из дома." },
      { id: "lav-fut-2", tense: "futuro", pronoun: "tu", it: "Lavorerai con noi?", ru: "Ты будешь работать с нами?" },
      { id: "lav-fut-3", tense: "futuro", pronoun: "lui", it: "Lui lavorerà in un'altra città.", ru: "Он будет работать в другом городе." },
      { id: "lav-fut-4", tense: "futuro", pronoun: "lei", it: "Lei lavorerà part-time.", ru: "Она будет работать неполный день." },
      { id: "lav-fut-5", tense: "futuro", pronoun: "noi", it: "Lavoreremo insieme sul progetto.", ru: "Мы будем работать над проектом вместе." },
      { id: "lav-fut-6", tense: "futuro", pronoun: "voi", it: "Lavorerete da remoto.", ru: "Вы будете работать удалённо." },
      { id: "lav-fut-7", tense: "futuro", pronoun: "loro", it: "Lavoreranno fino alle sei.", ru: "Они будут работать до шести." },
      { id: "lav-fut-8", tense: "futuro", pronoun: "io", it: "Non lavorerò il fine settimana.", ru: "Я не буду работать в выходные." },
      { id: "lav-fut-9", tense: "futuro", pronoun: "io", it: "Lavorerò di più il mese prossimo.", ru: "В следующем месяце я буду работать больше." },
      { id: "lav-fut-10", tense: "futuro", pronoun: "tu", it: "Quanto lavorerai domani?", ru: "Сколько ты будешь работать завтра?" },
    ],
  },
  {
    day: 2,
    verb: "parlare",
    translation: "говорить",
    phrases: [
      // Presente
      { id: "par-pre-1", tense: "presente", pronoun: "io", it: "Parlo italiano ogni giorno.", ru: "Я говорю по-итальянски каждый день." },
      { id: "par-pre-2", tense: "presente", pronoun: "tu", it: "Parli molto bene l'italiano.", ru: "Ты очень хорошо говоришь по-итальянски." },
      { id: "par-pre-3", tense: "presente", pronoun: "lui", it: "Lui parla tre lingue.", ru: "Он говорит на трёх языках." },
      { id: "par-pre-4", tense: "presente", pronoun: "lei", it: "Lei parla sempre con calma.", ru: "Она всегда говорит спокойно." },
      { id: "par-pre-5", tense: "presente", pronoun: "noi", it: "Parliamo italiano a casa.", ru: "Дома мы говорим по-итальянски." },
      { id: "par-pre-6", tense: "presente", pronoun: "voi", it: "Parlate troppo veloce.", ru: "Вы говорите слишком быстро." },
      { id: "par-pre-7", tense: "presente", pronoun: "loro", it: "Parlano tra di loro.", ru: "Они говорят между собой." },
      { id: "par-pre-8", tense: "presente", pronoun: "io", it: "Non parlo ancora perfettamente.", ru: "Я ещё не говорю идеально." },
      { id: "par-pre-9", tense: "presente", pronoun: "io", it: "Parlo con il mio coach ogni settimana.", ru: "Я говорю с тренером каждую неделю." },
      { id: "par-pre-10", tense: "presente", pronoun: "tu", it: "Con chi parli di solito?", ru: "С кем ты обычно говоришь?" },
      // Passato
      { id: "par-pas-1", tense: "passato", pronoun: "io", it: "Ieri ho parlato con il mio capo.", ru: "Вчера я говорил с начальником." },
      { id: "par-pas-2", tense: "passato", pronoun: "tu", it: "Hai parlato con lei?", ru: "Ты говорил с ней?" },
      { id: "par-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha parlato per un'ora.", ru: "Он говорил час." },
      { id: "par-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha parlato in italiano tutto il giorno.", ru: "Она говорила по-итальянски весь день." },
      { id: "par-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo parlato del progetto.", ru: "Мы говорили о проекте." },
      { id: "par-pas-6", tense: "passato", pronoun: "voi", it: "Avete parlato con il cliente?", ru: "Вы говорили с клиентом?" },
      { id: "par-pas-7", tense: "passato", pronoun: "loro", it: "Hanno parlato tutta la notte.", ru: "Они говорили всю ночь." },
      { id: "par-pas-8", tense: "passato", pronoun: "io", it: "Ho parlato troppo oggi.", ru: "Сегодня я говорил слишком много." },
      { id: "par-pas-9", tense: "passato", pronoun: "io", it: "Non ho parlato con nessuno ieri.", ru: "Вчера я ни с кем не говорил." },
      { id: "par-pas-10", tense: "passato", pronoun: "tu", it: "Di cosa hai parlato?", ru: "О чём ты говорил?" },
      // Imperfetto
      { id: "par-imp-1", tense: "imperfetto", pronoun: "io", it: "Da bambino parlavo solo russo.", ru: "В детстве я говорил только по-русски." },
      { id: "par-imp-2", tense: "imperfetto", pronoun: "tu", it: "Parlavi molto da piccolo.", ru: "В детстве ты много говорил." },
      { id: "par-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui parlava sempre di calcio.", ru: "Он всегда говорил о футболе." },
      { id: "par-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei parlava con tutti.", ru: "Она говорила со всеми." },
      { id: "par-imp-5", tense: "imperfetto", pronoun: "noi", it: "Parlavamo spesso di politica.", ru: "Мы часто говорили о политике." },
      { id: "par-imp-6", tense: "imperfetto", pronoun: "voi", it: "Parlavate sempre in russo.", ru: "Вы всегда говорили по-русски." },
      { id: "par-imp-7", tense: "imperfetto", pronoun: "loro", it: "Parlavano sottovoce.", ru: "Они говорили вполголоса." },
      { id: "par-imp-8", tense: "imperfetto", pronoun: "io", it: "Non parlavo mai in pubblico.", ru: "Я никогда не говорил публично." },
      { id: "par-imp-9", tense: "imperfetto", pronoun: "io", it: "Parlavo al telefono tutto il giorno.", ru: "Я говорил по телефону весь день." },
      { id: "par-imp-10", tense: "imperfetto", pronoun: "tu", it: "Di cosa parlavi con lui?", ru: "О чём ты с ним говорил?" },
      // Futuro
      { id: "par-fut-1", tense: "futuro", pronoun: "io", it: "La prossima settimana parlerò solo italiano.", ru: "На следующей неделе я буду говорить только по-итальянски." },
      { id: "par-fut-2", tense: "futuro", pronoun: "tu", it: "Parlerai con il direttore domani?", ru: "Завтра ты поговоришь с директором?" },
      { id: "par-fut-3", tense: "futuro", pronoun: "lui", it: "Lui parlerà alla conferenza.", ru: "Он будет говорить на конференции." },
      { id: "par-fut-4", tense: "futuro", pronoun: "lei", it: "Lei parlerà con i clienti.", ru: "Она будет говорить с клиентами." },
      { id: "par-fut-5", tense: "futuro", pronoun: "noi", it: "Parleremo di questo domani.", ru: "Мы поговорим об этом завтра." },
      { id: "par-fut-6", tense: "futuro", pronoun: "voi", it: "Parlerete con il team.", ru: "Вы будете говорить с командой." },
      { id: "par-fut-7", tense: "futuro", pronoun: "loro", it: "Parleranno in italiano.", ru: "Они будут говорить по-итальянски." },
      { id: "par-fut-8", tense: "futuro", pronoun: "io", it: "Parlerò più lentamente.", ru: "Я буду говорить медленнее." },
      { id: "par-fut-9", tense: "futuro", pronoun: "io", it: "Non parlerò di questo.", ru: "Я не буду об этом говорить." },
      { id: "par-fut-10", tense: "futuro", pronoun: "tu", it: "Con chi parlerai domani?", ru: "С кем ты будешь говорить завтра?" },
    ],
  },
  {
    day: 3,
    verb: "vivere",
    translation: "жить",
    phrases: [
      // Presente
      { id: "viv-pre-1", tense: "presente", pronoun: "io", it: "Vivo a Lugano con la mia famiglia.", ru: "Я живу в Лугано с семьёй." },
      { id: "viv-pre-2", tense: "presente", pronoun: "tu", it: "Dove vivi adesso?", ru: "Где ты сейчас живёшь?" },
      { id: "viv-pre-3", tense: "presente", pronoun: "lui", it: "Lui vive in centro.", ru: "Он живёт в центре." },
      { id: "viv-pre-4", tense: "presente", pronoun: "lei", it: "Lei vive da sola.", ru: "Она живёт одна." },
      { id: "viv-pre-5", tense: "presente", pronoun: "noi", it: "Viviamo in Svizzera da due anni.", ru: "Мы живём в Швейцарии два года." },
      { id: "viv-pre-6", tense: "presente", pronoun: "voi", it: "Vivete vicino al lago?", ru: "Вы живёте рядом с озером?" },
      { id: "viv-pre-7", tense: "presente", pronoun: "loro", it: "Vivono in un appartamento grande.", ru: "Они живут в большой квартире." },
      { id: "viv-pre-8", tense: "presente", pronoun: "io", it: "Vivo qui da un anno.", ru: "Я живу здесь уже год." },
      { id: "viv-pre-9", tense: "presente", pronoun: "io", it: "Non vivo più in Ucraina.", ru: "Я больше не живу на Украине." },
      { id: "viv-pre-10", tense: "presente", pronoun: "tu", it: "Con chi vivi?", ru: "С кем ты живёшь?" },
      // Passato
      { id: "viv-pas-1", tense: "passato", pronoun: "io", it: "Ho vissuto in Ucraina per trent'anni.", ru: "Я жил на Украине тридцать лет." },
      { id: "viv-pas-2", tense: "passato", pronoun: "tu", it: "Hai vissuto all'estero?", ru: "Ты жил за границей?" },
      { id: "viv-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha vissuto a Milano.", ru: "Он жил в Милане." },
      { id: "viv-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha vissuto da sola per anni.", ru: "Она жила одна много лет." },
      { id: "viv-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo vissuto in affitto.", ru: "Мы жили на съёмной квартире." },
      { id: "viv-pas-6", tense: "passato", pronoun: "voi", it: "Avete vissuto bene lì?", ru: "Вам хорошо жилось там?" },
      { id: "viv-pas-7", tense: "passato", pronoun: "loro", it: "Hanno vissuto in campagna.", ru: "Они жили в деревне." },
      { id: "viv-pas-8", tense: "passato", pronoun: "io", it: "Ho vissuto momenti difficili.", ru: "Я пережил трудные моменты." },
      { id: "viv-pas-9", tense: "passato", pronoun: "io", it: "Non ho mai vissuto da solo.", ru: "Я никогда не жил один." },
      { id: "viv-pas-10", tense: "passato", pronoun: "tu", it: "Dove hai vissuto prima?", ru: "Где ты жил раньше?" },
      // Imperfetto
      { id: "viv-imp-1", tense: "imperfetto", pronoun: "io", it: "Prima vivevo a Kiev.", ru: "Раньше я жил в Киеве." },
      { id: "viv-imp-2", tense: "imperfetto", pronoun: "tu", it: "Vivevi in centro?", ru: "Ты жил в центре?" },
      { id: "viv-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui viveva in una casa grande.", ru: "Он жил в большом доме." },
      { id: "viv-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei viveva con i genitori.", ru: "Она жила с родителями." },
      { id: "viv-imp-5", tense: "imperfetto", pronoun: "noi", it: "Vivevamo in un piccolo appartamento.", ru: "Мы жили в маленькой квартире." },
      { id: "viv-imp-6", tense: "imperfetto", pronoun: "voi", it: "Vivevate vicino al mare?", ru: "Вы жили рядом с морем?" },
      { id: "viv-imp-7", tense: "imperfetto", pronoun: "loro", it: "Vivevano semplicemente.", ru: "Они жили просто." },
      { id: "viv-imp-8", tense: "imperfetto", pronoun: "io", it: "Vivevo senza pensieri.", ru: "Я жил без забот." },
      { id: "viv-imp-9", tense: "imperfetto", pronoun: "io", it: "Non vivevo bene allora.", ru: "Тогда мне жилось нехорошо." },
      { id: "viv-imp-10", tense: "imperfetto", pronoun: "tu", it: "Come vivevi prima?", ru: "Как ты жил раньше?" },
      // Futuro
      { id: "viv-fut-1", tense: "futuro", pronoun: "io", it: "Un giorno vivrò in Italia.", ru: "Однажды я буду жить в Италии." },
      { id: "viv-fut-2", tense: "futuro", pronoun: "tu", it: "Dove vivrai tra cinque anni?", ru: "Где ты будешь жить через пять лет?" },
      { id: "viv-fut-3", tense: "futuro", pronoun: "lui", it: "Lui vivrà all'estero.", ru: "Он будет жить за границей." },
      { id: "viv-fut-4", tense: "futuro", pronoun: "lei", it: "Lei vivrà vicino ai figli.", ru: "Она будет жить рядом с детьми." },
      { id: "viv-fut-5", tense: "futuro", pronoun: "noi", it: "Vivremo meglio presto.", ru: "Скоро мы будем жить лучше." },
      { id: "viv-fut-6", tense: "futuro", pronoun: "voi", it: "Vivrete in Italia?", ru: "Вы будете жить в Италии?" },
      { id: "viv-fut-7", tense: "futuro", pronoun: "loro", it: "Vivranno in una casa nuova.", ru: "Они будут жить в новом доме." },
      { id: "viv-fut-8", tense: "futuro", pronoun: "io", it: "Vivrò dove mi sento bene.", ru: "Я буду жить там, где мне хорошо." },
      { id: "viv-fut-9", tense: "futuro", pronoun: "io", it: "Non vivrò sempre qui.", ru: "Я не буду жить здесь всегда." },
      { id: "viv-fut-10", tense: "futuro", pronoun: "tu", it: "Con chi vivrai?", ru: "С кем ты будешь жить?" },
    ],
  },
  {
    day: 4,
    verb: "studiare",
    translation: "учить/изучать",
    phrases: [
      // Presente
      { id: "stu-pre-1", tense: "presente", pronoun: "io", it: "Studio italiano ogni giorno.", ru: "Я учу итальянский каждый день." },
      { id: "stu-pre-2", tense: "presente", pronoun: "tu", it: "Studi molto ultimamente.", ru: "В последнее время ты много учишься." },
      { id: "stu-pre-3", tense: "presente", pronoun: "lui", it: "Lui studia medicina.", ru: "Он учится на врача." },
      { id: "stu-pre-4", tense: "presente", pronoun: "lei", it: "Lei studia tutto il giorno.", ru: "Она учится весь день." },
      { id: "stu-pre-5", tense: "presente", pronoun: "noi", it: "Studiamo insieme la sera.", ru: "Вечером мы учимся вместе." },
      { id: "stu-pre-6", tense: "presente", pronoun: "voi", it: "Studiate abbastanza?", ru: "Вы достаточно учитесь?" },
      { id: "stu-pre-7", tense: "presente", pronoun: "loro", it: "Studiano in biblioteca.", ru: "Они учатся в библиотеке." },
      { id: "stu-pre-8", tense: "presente", pronoun: "io", it: "Studio con un'app ogni mattina.", ru: "Каждое утро я учусь с приложением." },
      { id: "stu-pre-9", tense: "presente", pronoun: "io", it: "Non studio la grammatica classica.", ru: "Я не учу классическую грамматику." },
      { id: "stu-pre-10", tense: "presente", pronoun: "tu", it: "Quanto studi al giorno?", ru: "Сколько ты учишься в день?" },
      // Passato
      { id: "stu-pas-1", tense: "passato", pronoun: "io", it: "Ho studiato italiano per un anno.", ru: "Я учил итальянский год." },
      { id: "stu-pas-2", tense: "passato", pronoun: "tu", it: "Hai studiato oggi?", ru: "Ты учился сегодня?" },
      { id: "stu-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha studiato tutta la notte.", ru: "Он учился всю ночь." },
      { id: "stu-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha studiato all'università.", ru: "Она училась в университете." },
      { id: "stu-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo studiato insieme ieri.", ru: "Вчера мы учились вместе." },
      { id: "stu-pas-6", tense: "passato", pronoun: "voi", it: "Avete studiato per l'esame?", ru: "Вы учились к экзамену?" },
      { id: "stu-pas-7", tense: "passato", pronoun: "loro", it: "Hanno studiato molto.", ru: "Они много учились." },
      { id: "stu-pas-8", tense: "passato", pronoun: "io", it: "Ho studiato tre ore oggi.", ru: "Сегодня я учился три часа." },
      { id: "stu-pas-9", tense: "passato", pronoun: "io", it: "Non ho studiato ieri sera.", ru: "Вчера вечером я не учился." },
      { id: "stu-pas-10", tense: "passato", pronoun: "tu", it: "Cosa hai studiato?", ru: "Что ты учил?" },
      // Imperfetto
      { id: "stu-imp-1", tense: "imperfetto", pronoun: "io", it: "Da giovane studiavo molto.", ru: "В молодости я много учился." },
      { id: "stu-imp-2", tense: "imperfetto", pronoun: "tu", it: "Studiavi bene a scuola?", ru: "Ты хорошо учился в школе?" },
      { id: "stu-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui studiava sempre di notte.", ru: "Он всегда учился ночью." },
      { id: "stu-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei studiava lingue straniere.", ru: "Она учила иностранные языки." },
      { id: "stu-imp-5", tense: "imperfetto", pronoun: "noi", it: "Studiavamo insieme ogni sera.", ru: "Каждый вечер мы учились вместе." },
      { id: "stu-imp-6", tense: "imperfetto", pronoun: "voi", it: "Studiavate molto al liceo?", ru: "Вы много учились в лицее?" },
      { id: "stu-imp-7", tense: "imperfetto", pronoun: "loro", it: "Studiavano senza sosta.", ru: "Они учились без остановки." },
      { id: "stu-imp-8", tense: "imperfetto", pronoun: "io", it: "Studiavo musica da bambino.", ru: "В детстве я учился музыке." },
      { id: "stu-imp-9", tense: "imperfetto", pronoun: "io", it: "Non studiavo abbastanza allora.", ru: "Тогда я учился недостаточно." },
      { id: "stu-imp-10", tense: "imperfetto", pronoun: "tu", it: "Cosa studiavi all'università?", ru: "Что ты учил в университете?" },
      // Futuro
      { id: "stu-fut-1", tense: "futuro", pronoun: "io", it: "Studierò italiano fino alla perfezione.", ru: "Я буду учить итальянский до совершенства." },
      { id: "stu-fut-2", tense: "futuro", pronoun: "tu", it: "Studierai ancora?", ru: "Ты будешь ещё учиться?" },
      { id: "stu-fut-3", tense: "futuro", pronoun: "lui", it: "Lui studierà all'estero.", ru: "Он будет учиться за границей." },
      { id: "stu-fut-4", tense: "futuro", pronoun: "lei", it: "Lei studierà medicina.", ru: "Она будет учиться на врача." },
      { id: "stu-fut-5", tense: "futuro", pronoun: "noi", it: "Studieremo insieme il fine settimana.", ru: "В выходные мы будем учиться вместе." },
      { id: "stu-fut-6", tense: "futuro", pronoun: "voi", it: "Studierete per l'esame?", ru: "Вы будете учиться к экзамену?" },
      { id: "stu-fut-7", tense: "futuro", pronoun: "loro", it: "Studieranno una lingua nuova.", ru: "Они будут учить новый язык." },
      { id: "stu-fut-8", tense: "futuro", pronoun: "io", it: "Studierò ogni giorno senza eccezioni.", ru: "Я буду учиться каждый день без исключений." },
      { id: "stu-fut-9", tense: "futuro", pronoun: "io", it: "Non studierò dalla teoria.", ru: "Я не буду учиться по теории." },
      { id: "stu-fut-10", tense: "futuro", pronoun: "tu", it: "Quanto studierai domani?", ru: "Сколько ты будешь учиться завтра?" },
    ],
  },
  {
    day: 5,
    verb: "capire",
    translation: "понимать",
    phrases: [
      // Presente
      { id: "cap-pre-1", tense: "presente", pronoun: "io", it: "Capisco abbastanza bene l'italiano.", ru: "Я достаточно хорошо понимаю итальянский." },
      { id: "cap-pre-2", tense: "presente", pronoun: "tu", it: "Capisci quello che dico?", ru: "Ты понимаешь что я говорю?" },
      { id: "cap-pre-3", tense: "presente", pronoun: "lui", it: "Lui capisce tutto subito.", ru: "Он всё понимает сразу." },
      { id: "cap-pre-4", tense: "presente", pronoun: "lei", it: "Lei capisce senza traduzione.", ru: "Она понимает без перевода." },
      { id: "cap-pre-5", tense: "presente", pronoun: "noi", it: "Capiamo meglio ogni giorno.", ru: "Каждый день мы понимаем лучше." },
      { id: "cap-pre-6", tense: "presente", pronoun: "voi", it: "Capite l'italiano parlato?", ru: "Вы понимаете разговорный итальянский?" },
      { id: "cap-pre-7", tense: "presente", pronoun: "loro", it: "Capiscono tutto ma non parlano.", ru: "Они всё понимают но не говорят." },
      { id: "cap-pre-8", tense: "presente", pronoun: "io", it: "Non capisco ancora tutto.", ru: "Я ещё не всё понимаю." },
      { id: "cap-pre-9", tense: "presente", pronoun: "io", it: "Capisco di più quando parlano lentamente.", ru: "Я лучше понимаю когда говорят медленно." },
      { id: "cap-pre-10", tense: "presente", pronoun: "tu", it: "Capisci il dialetto?", ru: "Ты понимаешь диалект?" },
      // Passato
      { id: "cap-pas-1", tense: "passato", pronoun: "io", it: "Ho capito finalmente.", ru: "Наконец-то я понял." },
      { id: "cap-pas-2", tense: "passato", pronoun: "tu", it: "Hai capito la spiegazione?", ru: "Ты понял объяснение?" },
      { id: "cap-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha capito subito.", ru: "Он понял сразу." },
      { id: "cap-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha capito il problema.", ru: "Она поняла проблему." },
      { id: "cap-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo capito l'errore.", ru: "Мы поняли ошибку." },
      { id: "cap-pas-6", tense: "passato", pronoun: "voi", it: "Avete capito la lezione?", ru: "Вы поняли урок?" },
      { id: "cap-pas-7", tense: "passato", pronoun: "loro", it: "Hanno capito tardi.", ru: "Они поняли поздно." },
      { id: "cap-pas-8", tense: "passato", pronoun: "io", it: "Non ho capito niente ieri.", ru: "Вчера я ничего не понял." },
      { id: "cap-pas-9", tense: "passato", pronoun: "io", it: "Ho capito come funziona.", ru: "Я понял как это работает." },
      { id: "cap-pas-10", tense: "passato", pronoun: "tu", it: "Hai capito cosa intendevo?", ru: "Ты понял что я имел в виду?" },
      // Imperfetto
      { id: "cap-imp-1", tense: "imperfetto", pronoun: "io", it: "Prima non capivo niente.", ru: "Раньше я ничего не понимал." },
      { id: "cap-imp-2", tense: "imperfetto", pronoun: "tu", it: "Capivi tutto quello che dicevano?", ru: "Ты понимал всё что они говорили?" },
      { id: "cap-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui capiva senza spiegazioni.", ru: "Он понимал без объяснений." },
      { id: "cap-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei capiva subito i problemi.", ru: "Она сразу понимала проблемы." },
      { id: "cap-imp-5", tense: "imperfetto", pronoun: "noi", it: "Non capivamo il dialetto.", ru: "Мы не понимали диалект." },
      { id: "cap-imp-6", tense: "imperfetto", pronoun: "voi", it: "Capivate l'italiano alla TV?", ru: "Вы понимали итальянский по телевизору?" },
      { id: "cap-imp-7", tense: "imperfetto", pronoun: "loro", it: "Capivano poco all'inizio.", ru: "Вначале они мало понимали." },
      { id: "cap-imp-8", tense: "imperfetto", pronoun: "io", it: "Non capivo perché studiare la grammatica.", ru: "Я не понимал зачем учить грамматику." },
      { id: "cap-imp-9", tense: "imperfetto", pronoun: "io", it: "Capivo meglio scritto che parlato.", ru: "Письменный я понимал лучше чем устный." },
      { id: "cap-imp-10", tense: "imperfetto", pronoun: "tu", it: "Capivi quando parlava veloce?", ru: "Ты понимал когда он говорил быстро?" },
      // Futuro
      { id: "cap-fut-1", tense: "futuro", pronoun: "io", it: "Un giorno capirò tutto.", ru: "Однажды я буду понимать всё." },
      { id: "cap-fut-2", tense: "futuro", pronoun: "tu", it: "Capirai presto.", ru: "Скоро ты будешь понимать." },
      { id: "cap-fut-3", tense: "futuro", pronoun: "lui", it: "Lui capirà con la pratica.", ru: "Он будет понимать с практикой." },
      { id: "cap-fut-4", tense: "futuro", pronoun: "lei", it: "Lei capirà meglio col tempo.", ru: "Со временем она будет понимать лучше." },
      { id: "cap-fut-5", tense: "futuro", pronoun: "noi", it: "Capiremo di più dopo questo corso.", ru: "После этого курса мы будем понимать больше." },
      { id: "cap-fut-6", tense: "futuro", pronoun: "voi", it: "Capirete tutto alla fine.", ru: "В конце вы будете всё понимать." },
      { id: "cap-fut-7", tense: "futuro", pronoun: "loro", it: "Capiranno quando praticheranno.", ru: "Они будут понимать когда будут практиковаться." },
      { id: "cap-fut-8", tense: "futuro", pronoun: "io", it: "Capirò senza dizionario.", ru: "Я буду понимать без словаря." },
      { id: "cap-fut-9", tense: "futuro", pronoun: "io", it: "Non capirò mai il napoletano.", ru: "Я никогда не буду понимать неаполитанский." },
      { id: "cap-fut-10", tense: "futuro", pronoun: "tu", it: "Capirai l'italiano dei film?", ru: "Ты будешь понимать итальянский в фильмах?" },
    ],
  },
  {
    day: 6,
    verb: "andare",
    translation: "идти/ехать",
    phrases: [
      // Presente
      { id: "and-pre-1", tense: "presente", pronoun: "io", it: "Vado a lavorare alle nove.", ru: "Я иду на работу в девять." },
      { id: "and-pre-2", tense: "presente", pronoun: "tu", it: "Dove vai oggi?", ru: "Куда ты идёшь сегодня?" },
      { id: "and-pre-3", tense: "presente", pronoun: "lui", it: "Lui va in palestra ogni giorno.", ru: "Он ходит в спортзал каждый день." },
      { id: "and-pre-4", tense: "presente", pronoun: "lei", it: "Lei va al mercato ogni sabato.", ru: "Она ходит на рынок каждую субботу." },
      { id: "and-pre-5", tense: "presente", pronoun: "noi", it: "Andiamo al ristorante stasera.", ru: "Сегодня вечером мы идём в ресторан." },
      { id: "and-pre-6", tense: "presente", pronoun: "voi", it: "Andate spesso al lago?", ru: "Вы часто ходите к озеру?" },
      { id: "and-pre-7", tense: "presente", pronoun: "loro", it: "Vanno in vacanza ogni estate.", ru: "Каждое лето они едут в отпуск." },
      { id: "and-pre-8", tense: "presente", pronoun: "io", it: "Non vado mai in ufficio.", ru: "Я никогда не хожу в офис." },
      { id: "and-pre-9", tense: "presente", pronoun: "io", it: "Vado a prendere un caffè.", ru: "Я иду за кофе." },
      { id: "and-pre-10", tense: "presente", pronoun: "tu", it: "A che ora vai a dormire?", ru: "В котором часу ты ложишься спать?" },
      // Passato
      { id: "and-pas-1", tense: "passato", pronoun: "io", it: "Ieri sono andato al supermercato.", ru: "Вчера я ходил в супермаркет." },
      { id: "and-pas-2", tense: "passato", pronoun: "tu", it: "Sei andato dal medico?", ru: "Ты ходил к врачу?" },
      { id: "and-pas-3", tense: "passato", pronoun: "lui", it: "Lui è andato a Milano.", ru: "Он поехал в Милан." },
      { id: "and-pas-4", tense: "passato", pronoun: "lei", it: "Lei è andata a trovare gli amici.", ru: "Она пошла навестить друзей." },
      { id: "and-pas-5", tense: "passato", pronoun: "noi", it: "Siamo andati al lago domenica.", ru: "В воскресенье мы ходили к озеру." },
      { id: "and-pas-6", tense: "passato", pronoun: "voi", it: "Siete andati in vacanza?", ru: "Вы ездили в отпуск?" },
      { id: "and-pas-7", tense: "passato", pronoun: "loro", it: "Sono andati al cinema ieri.", ru: "Вчера они ходили в кино." },
      { id: "and-pas-8", tense: "passato", pronoun: "io", it: "Sono andato a dormire tardi.", ru: "Я лёг спать поздно." },
      { id: "and-pas-9", tense: "passato", pronoun: "io", it: "Non sono andato in ufficio oggi.", ru: "Сегодня я не ходил в офис." },
      { id: "and-pas-10", tense: "passato", pronoun: "tu", it: "Dove sei andato ieri sera?", ru: "Куда ты ходил вчера вечером?" },
      // Imperfetto
      { id: "and-imp-1", tense: "imperfetto", pronoun: "io", it: "Prima andavo in ufficio ogni giorno.", ru: "Раньше я ходил в офис каждый день." },
      { id: "and-imp-2", tense: "imperfetto", pronoun: "tu", it: "Andavi spesso al mare?", ru: "Ты часто ходил на море?" },
      { id: "and-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui andava in palestra tre volte a settimana.", ru: "Он ходил в спортзал три раза в неделю." },
      { id: "and-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei andava a scuola a piedi.", ru: "Она ходила в школу пешком." },
      { id: "and-imp-5", tense: "imperfetto", pronoun: "noi", it: "Andavamo al parco ogni domenica.", ru: "Каждое воскресенье мы ходили в парк." },
      { id: "and-imp-6", tense: "imperfetto", pronoun: "voi", it: "Andavate spesso al ristorante?", ru: "Вы часто ходили в ресторан?" },
      { id: "and-imp-7", tense: "imperfetto", pronoun: "loro", it: "Andavano in vacanza ogni anno.", ru: "Каждый год они ездили в отпуск." },
      { id: "and-imp-8", tense: "imperfetto", pronoun: "io", it: "Non andavo mai in discoteca.", ru: "Я никогда не ходил на дискотеку." },
      { id: "and-imp-9", tense: "imperfetto", pronoun: "io", it: "Andavo a correre ogni mattina.", ru: "Каждое утро я ходил бегать." },
      { id: "and-imp-10", tense: "imperfetto", pronoun: "tu", it: "Dove andavi in vacanza?", ru: "Куда ты ездил в отпуск?" },
      // Futuro
      { id: "and-fut-1", tense: "futuro", pronoun: "io", it: "Domani andrò dal dentista.", ru: "Завтра я пойду к стоматологу." },
      { id: "and-fut-2", tense: "futuro", pronoun: "tu", it: "Dove andrai questa estate?", ru: "Куда ты поедешь этим летом?" },
      { id: "and-fut-3", tense: "futuro", pronoun: "lui", it: "Lui andrà a Roma la prossima settimana.", ru: "На следующей неделе он поедет в Рим." },
      { id: "and-fut-4", tense: "futuro", pronoun: "lei", it: "Lei andrà all'estero.", ru: "Она поедет за границу." },
      { id: "and-fut-5", tense: "futuro", pronoun: "noi", it: "Andremo in Italia il prossimo anno.", ru: "В следующем году мы поедем в Италию." },
      { id: "and-fut-6", tense: "futuro", pronoun: "voi", it: "Andrete al mare quest'estate?", ru: "Вы поедете на море этим летом?" },
      { id: "and-fut-7", tense: "futuro", pronoun: "loro", it: "Andranno a vivere in campagna.", ru: "Они уедут жить в деревню." },
      { id: "and-fut-8", tense: "futuro", pronoun: "io", it: "Non andrò da nessuna parte questo weekend.", ru: "В эти выходные я никуда не пойду." },
      { id: "and-fut-9", tense: "futuro", pronoun: "io", it: "Andrò a trovare i miei amici.", ru: "Я пойду навестить своих друзей." },
      { id: "and-fut-10", tense: "futuro", pronoun: "tu", it: "Con chi andrai in vacanza?", ru: "С кем ты поедешь в отпуск?" },
    ],
  },
  {
    day: 7,
    verb: "volere",
    translation: "хотеть",
    phrases: [
      // Presente
      { id: "vol-pre-1", tense: "presente", pronoun: "io", it: "Voglio parlare italiano fluentemente.", ru: "Я хочу говорить по-итальянски свободно." },
      { id: "vol-pre-2", tense: "presente", pronoun: "tu", it: "Cosa vuoi fare oggi?", ru: "Что ты хочешь делать сегодня?" },
      { id: "vol-pre-3", tense: "presente", pronoun: "lui", it: "Lui vuole cambiare lavoro.", ru: "Он хочет сменить работу." },
      { id: "vol-pre-4", tense: "presente", pronoun: "lei", it: "Lei vuole imparare a cucinare.", ru: "Она хочет научиться готовить." },
      { id: "vol-pre-5", tense: "presente", pronoun: "noi", it: "Vogliamo vivere in Italia.", ru: "Мы хотим жить в Италии." },
      { id: "vol-pre-6", tense: "presente", pronoun: "voi", it: "Volete venire con noi?", ru: "Вы хотите пойти с нами?" },
      { id: "vol-pre-7", tense: "presente", pronoun: "loro", it: "Vogliono comprare una casa.", ru: "Они хотят купить дом." },
      { id: "vol-pre-8", tense: "presente", pronoun: "io", it: "Non voglio perdere tempo.", ru: "Я не хочу тратить время." },
      { id: "vol-pre-9", tense: "presente", pronoun: "io", it: "Voglio migliorare ogni giorno.", ru: "Я хочу улучшаться каждый день." },
      { id: "vol-pre-10", tense: "presente", pronoun: "tu", it: "Vuoi un caffè?", ru: "Ты хочешь кофе?" },
      // Passato
      { id: "vol-pas-1", tense: "passato", pronoun: "io", it: "Ho voluto cambiare vita.", ru: "Я захотел изменить жизнь." },
      { id: "vol-pas-2", tense: "passato", pronoun: "tu", it: "Hai voluto venire tu?", ru: "Ты сам захотел прийти?" },
      { id: "vol-pas-3", tense: "passato", pronoun: "lui", it: "Lui ha voluto farlo da solo.", ru: "Он захотел сделать это сам." },
      { id: "vol-pas-4", tense: "passato", pronoun: "lei", it: "Lei ha voluto restare.", ru: "Она захотела остаться." },
      { id: "vol-pas-5", tense: "passato", pronoun: "noi", it: "Abbiamo voluto provare.", ru: "Мы захотели попробовать." },
      { id: "vol-pas-6", tense: "passato", pronoun: "voi", it: "Avete voluto cambiare tutto.", ru: "Вы захотели изменить всё." },
      { id: "vol-pas-7", tense: "passato", pronoun: "loro", it: "Hanno voluto aiutare.", ru: "Они захотели помочь." },
      { id: "vol-pas-8", tense: "passato", pronoun: "io", it: "Ho voluto imparare l'italiano.", ru: "Я захотел выучить итальянский." },
      { id: "vol-pas-9", tense: "passato", pronoun: "io", it: "Non ho voluto arrendermi.", ru: "Я не захотел сдаваться." },
      { id: "vol-pas-10", tense: "passato", pronoun: "tu", it: "Perché hai voluto farlo?", ru: "Почему ты захотел это сделать?" },
      // Imperfetto
      { id: "vol-imp-1", tense: "imperfetto", pronoun: "io", it: "Volevo sempre vivere in Italia.", ru: "Я всегда хотел жить в Италии." },
      { id: "vol-imp-2", tense: "imperfetto", pronoun: "tu", it: "Cosa volevi fare da grande?", ru: "Кем ты хотел стать в детстве?" },
      { id: "vol-imp-3", tense: "imperfetto", pronoun: "lui", it: "Lui voleva diventare medico.", ru: "Он хотел стать врачом." },
      { id: "vol-imp-4", tense: "imperfetto", pronoun: "lei", it: "Lei voleva studiare arte.", ru: "Она хотела изучать искусство." },
      { id: "vol-imp-5", tense: "imperfetto", pronoun: "noi", it: "Volevamo cambiare le cose.", ru: "Мы хотели изменить ситуацию." },
      { id: "vol-imp-6", tense: "imperfetto", pronoun: "voi", it: "Volevate partire prima.", ru: "Вы хотели уехать раньше." },
      { id: "vol-imp-7", tense: "imperfetto", pronoun: "loro", it: "Volevano restare insieme.", ru: "Они хотели остаться вместе." },
      { id: "vol-imp-8", tense: "imperfetto", pronoun: "io", it: "Non volevo rinunciare ai miei sogni.", ru: "Я не хотел отказываться от своих мечт." },
      { id: "vol-imp-9", tense: "imperfetto", pronoun: "io", it: "Volevo imparare tante cose.", ru: "Я хотел научиться многому." },
      { id: "vol-imp-10", tense: "imperfetto", pronoun: "tu", it: "Volevi venire o no?", ru: "Ты хотел прийти или нет?" },
      // Futuro
      { id: "vol-fut-1", tense: "futuro", pronoun: "io", it: "Vorrò sempre migliorare.", ru: "Я всегда буду хотеть улучшаться." },
      { id: "vol-fut-2", tense: "futuro", pronoun: "tu", it: "Vorrai ancora farlo tra un anno?", ru: "Ты захочешь делать это через год?" },
      { id: "vol-fut-3", tense: "futuro", pronoun: "lui", it: "Lui vorrà di più col tempo.", ru: "Со временем он захочет большего." },
      { id: "vol-fut-4", tense: "futuro", pronoun: "lei", it: "Lei vorrà tornare un giorno.", ru: "Однажды она захочет вернуться." },
      { id: "vol-fut-5", tense: "futuro", pronoun: "noi", it: "Vorremo vivere meglio.", ru: "Мы захотим жить лучше." },
      { id: "vol-fut-6", tense: "futuro", pronoun: "voi", it: "Vorrete cambiare idea.", ru: "Вы захотите изменить мнение." },
      { id: "vol-fut-7", tense: "futuro", pronoun: "loro", it: "Vorranno restare in Italia.", ru: "Они захотят остаться в Италии." },
      { id: "vol-fut-8", tense: "futuro", pronoun: "io", it: "Non vorrò mai smettere di imparare.", ru: "Я никогда не захочу перестать учиться." },
      { id: "vol-fut-9", tense: "futuro", pronoun: "io", it: "Vorrò parlare con i madrelingua.", ru: "Я захочу говорить с носителями языка." },
      { id: "vol-fut-10", tense: "futuro", pronoun: "tu", it: "Cosa vorrai fare dopo?", ru: "Что ты захочешь делать потом?" },
    ],
  },
];
