export type CEFRLevel = "A1" | "A2" | "B1";

export type Phrase = {
  id: string;
  it: string;
  ru: string;
  context: string;
  difficulty: number;
  tags: string[];
  level: CEFRLevel;
};

export type LanguagePack = {
  code: string;
  name: string;
  phrases: Phrase[];
  voice: string;
};

export const italianPack: LanguagePack = {
  code: "it",
  name: "Italiano",
  voice: "it-IT",
  phrases: [
    // ─── ДЕНЬ 1: Знакомство — произношение, essere/avere, частотные слова ───
    {
      id: "pron1",
      it: "Voglio imparare l'italiano.",
      ru: "Я хочу выучить итальянский.",
      context: "Произношение: gli",
      difficulty: 1,
      tags: ["pronunciation", "gli", "day-1"],
      level: "A1",
    },
    {
      id: "pron2",
      it: "Ho bisogno di tempo libero.",
      ru: "Мне нужно свободное время.",
      context: "Произношение: gn",
      difficulty: 2,
      tags: ["pronunciation", "gn", "day-1"],
      level: "A2",
    },
    {
      id: "pron3",
      it: "Che cosa fai oggi?",
      ru: "Что ты делаешь сегодня?",
      context: "Произношение: che",
      difficulty: 1,
      tags: ["pronunciation", "che", "day-1"],
      level: "A1",
    },
    {
      id: "pron4",
      it: "Chi sei?",
      ru: "Кто ты?",
      context: "Произношение: chi",
      difficulty: 1,
      tags: ["pronunciation", "chi", "day-1"],
      level: "A1",
    },
    {
      id: "pron5",
      it: "Lascio il lavoro alle sei.",
      ru: "Я заканчиваю работу в шесть.",
      context: "Произношение: sci",
      difficulty: 2,
      tags: ["pronunciation", "sci", "day-1"],
      level: "A2",
    },
    {
      id: "pron6",
      it: "Mangio il pesce la sera.",
      ru: "Вечером я ем рыбу.",
      context: "Произношение: sce",
      difficulty: 2,
      tags: ["pronunciation", "sce", "day-1"],
      level: "A2",
    },
    {
      id: "ess1",
      it: "Sono pronto a parlare.",
      ru: "Я готов говорить.",
      context: "Essere — io",
      difficulty: 1,
      tags: ["verb-essere", "presente", "day-1"],
      level: "A1",
    },
    {
      id: "ess2",
      it: "Sei stanco oggi?",
      ru: "Ты устал сегодня?",
      context: "Essere — tu",
      difficulty: 1,
      tags: ["verb-essere", "presente", "day-1"],
      level: "A1",
    },
    {
      id: "av1",
      it: "Ho una domanda.",
      ru: "У меня есть вопрос.",
      context: "Avere — io",
      difficulty: 1,
      tags: ["verb-avere", "presente", "day-1"],
      level: "A1",
    },
    {
      id: "av2",
      it: "Hai tempo adesso?",
      ru: "У тебя есть время сейчас?",
      context: "Avere — tu",
      difficulty: 1,
      tags: ["verb-avere", "presente", "day-1"],
      level: "A1",
    },
    {
      id: "f1",
      it: "Vivo qui da un anno.",
      ru: "Я живу здесь уже год.",
      context: "Частые слова: vivere",
      difficulty: 2,
      tags: ["frequency", "vivere", "day-1"],
      level: "A2",
    },
    {
      id: "f2",
      it: "Il mio lavoro è interessante.",
      ru: "Моя работа интересная.",
      context: "Частые слова: lavoro",
      difficulty: 1,
      tags: ["frequency", "lavoro", "day-1"],
      level: "A1",
    },

    // ─── ДЕНЬ 2: В кафе — заказ, оплата, вежливые фразы ───
    {
      id: "d2-1",
      it: "Vorrei un caffè, per favore.",
      ru: "Я бы хотел кофе, пожалуйста.",
      context: "Заказ: vorrei",
      difficulty: 1,
      tags: ["cafe", "order", "day-2"],
      level: "A1",
    },
    {
      id: "d2-2",
      it: "Quant'è?",
      ru: "Сколько стоит?",
      context: "Оплата",
      difficulty: 1,
      tags: ["cafe", "price", "day-2"],
      level: "A1",
    },
    {
      id: "d2-3",
      it: "Posso avere il menu?",
      ru: "Можно мне меню?",
      context: "В кафе: просьба",
      difficulty: 1,
      tags: ["cafe", "request", "day-2"],
      level: "A1",
    },
    {
      id: "d2-4",
      it: "Prendo anche un cornetto.",
      ru: "Я возьму ещё круассан.",
      context: "Заказ еды",
      difficulty: 1,
      tags: ["cafe", "food", "day-2"],
      level: "A1",
    },
    {
      id: "d2-5",
      it: "C'è qualcosa da mangiare?",
      ru: "Есть что-нибудь поесть?",
      context: "В кафе: вопрос",
      difficulty: 2,
      tags: ["cafe", "food", "day-2"],
      level: "A2",
    },
    {
      id: "d2-6",
      it: "Pago con la carta.",
      ru: "Плачу картой.",
      context: "Оплата картой",
      difficulty: 1,
      tags: ["cafe", "payment", "day-2"],
      level: "A1",
    },
    {
      id: "d2-7",
      it: "È molto buono, grazie!",
      ru: "Это очень вкусно, спасибо!",
      context: "Отзыв о еде",
      difficulty: 1,
      tags: ["cafe", "compliment", "day-2"],
      level: "A1",
    },

    // ─── ДЕНЬ 3: На работе — коллеги, проекты, рабочие фразы ───
    {
      id: "d3-1",
      it: "Lavoro in un'azienda tecnologica.",
      ru: "Я работаю в технологической компании.",
      context: "О работе",
      difficulty: 2,
      tags: ["work", "company", "day-3"],
      level: "A2",
    },
    {
      id: "d3-2",
      it: "Ho una riunione alle tre.",
      ru: "У меня встреча в три.",
      context: "Рабочий день",
      difficulty: 1,
      tags: ["work", "meeting", "day-3"],
      level: "A1",
    },
    {
      id: "d3-3",
      it: "Stiamo lavorando su un nuovo progetto.",
      ru: "Мы работаем над новым проектом.",
      context: "Проект: stare + gerundio",
      difficulty: 2,
      tags: ["work", "project", "day-3"],
      level: "A2",
    },
    {
      id: "d3-4",
      it: "Mi occupo di sviluppo software.",
      ru: "Я занимаюсь разработкой программного обеспечения.",
      context: "Специализация",
      difficulty: 2,
      tags: ["work", "tech", "day-3"],
      level: "A2",
    },
    {
      id: "d3-5",
      it: "Possiamo parlarne domani?",
      ru: "Можем поговорить об этом завтра?",
      context: "Перенос разговора",
      difficulty: 2,
      tags: ["work", "schedule", "day-3"],
      level: "A2",
    },
    {
      id: "d3-6",
      it: "Mando il report entro oggi.",
      ru: "Пришлю отчёт к сегодняшнему дню.",
      context: "Дедлайн",
      difficulty: 2,
      tags: ["work", "deadline", "day-3"],
      level: "A2",
    },
    {
      id: "d3-7",
      it: "Sei disponibile per una chiamata?",
      ru: "Ты доступен для звонка?",
      context: "Онлайн-встреча",
      difficulty: 2,
      tags: ["work", "call", "day-3"],
      level: "A2",
    },

    // ─── ДЕНЬ 4: В магазине — покупки, цены, количество ───
    {
      id: "d4-1",
      it: "Cerco del pane fresco.",
      ru: "Я ищу свежий хлеб.",
      context: "В магазине: cercare",
      difficulty: 1,
      tags: ["shop", "food", "day-4"],
      level: "A1",
    },
    {
      id: "d4-2",
      it: "Quanto costa questo?",
      ru: "Сколько это стоит?",
      context: "Цена товара",
      difficulty: 1,
      tags: ["shop", "price", "day-4"],
      level: "A1",
    },
    {
      id: "d4-3",
      it: "Vorrei un chilo di pomodori.",
      ru: "Я хотел бы килограмм помидоров.",
      context: "Количество: chilo",
      difficulty: 1,
      tags: ["shop", "quantity", "day-4"],
      level: "A1",
    },
    {
      id: "d4-4",
      it: "Avete latte di soia?",
      ru: "У вас есть соевое молоко?",
      context: "Поиск товара",
      difficulty: 2,
      tags: ["shop", "food", "day-4"],
      level: "A2",
    },
    {
      id: "d4-5",
      it: "Mi serve anche del latte.",
      ru: "Мне нужно ещё молоко.",
      context: "Дополнительный товар",
      difficulty: 1,
      tags: ["shop", "food", "day-4"],
      level: "A1",
    },
    {
      id: "d4-6",
      it: "Posso avere un sacchetto?",
      ru: "Можно пакет?",
      context: "Упаковка",
      difficulty: 1,
      tags: ["shop", "request", "day-4"],
      level: "A1",
    },
    {
      id: "d4-7",
      it: "È troppo caro per me.",
      ru: "Это слишком дорого для меня.",
      context: "Цена: troppo caro",
      difficulty: 2,
      tags: ["shop", "price", "day-4"],
      level: "A2",
    },

    // ─── ДЕНЬ 5: Транспорт — ориентация, расписание, время ───
    {
      id: "d5-1",
      it: "Scusi, dov'è la stazione?",
      ru: "Извините, где вокзал?",
      context: "Ориентация в городе",
      difficulty: 1,
      tags: ["transport", "directions", "day-5"],
      level: "A1",
    },
    {
      id: "d5-2",
      it: "Quanto tempo ci vuole?",
      ru: "Сколько времени займёт?",
      context: "Время в пути",
      difficulty: 2,
      tags: ["transport", "time", "day-5"],
      level: "A2",
    },
    {
      id: "d5-3",
      it: "Questo autobus va in centro?",
      ru: "Этот автобус едет в центр?",
      context: "Маршрут автобуса",
      difficulty: 1,
      tags: ["transport", "bus", "day-5"],
      level: "A1",
    },
    {
      id: "d5-4",
      it: "A che ora parte il prossimo treno?",
      ru: "В котором часу отходит следующий поезд?",
      context: "Расписание поездов",
      difficulty: 2,
      tags: ["transport", "train", "schedule", "day-5"],
      level: "A2",
    },
    {
      id: "d5-5",
      it: "Devo scendere alla prossima fermata.",
      ru: "Мне нужно выйти на следующей остановке.",
      context: "В автобусе",
      difficulty: 2,
      tags: ["transport", "bus", "day-5"],
      level: "A2",
    },
    {
      id: "d5-6",
      it: "Dove posso comprare il biglietto?",
      ru: "Где я могу купить билет?",
      context: "Билет на транспорт",
      difficulty: 2,
      tags: ["transport", "ticket", "day-5"],
      level: "A2",
    },
    {
      id: "d5-7",
      it: "Il treno è in ritardo di dieci minuti.",
      ru: "Поезд опаздывает на десять минут.",
      context: "Опоздание транспорта",
      difficulty: 2,
      tags: ["transport", "delay", "day-5"],
      level: "A2",
    },

    // ─── ДЕНЬ 6: У врача — здоровье, симптомы, запись ───
    {
      id: "d6-1",
      it: "Non mi sento bene.",
      ru: "Я плохо себя чувствую.",
      context: "Самочувствие",
      difficulty: 1,
      tags: ["health", "symptoms", "day-6"],
      level: "A1",
    },
    {
      id: "d6-2",
      it: "Ho la febbre da due giorni.",
      ru: "У меня температура уже два дня.",
      context: "Симптомы: febbre",
      difficulty: 2,
      tags: ["health", "symptoms", "day-6"],
      level: "A2",
    },
    {
      id: "d6-3",
      it: "Mi fa male la testa.",
      ru: "У меня болит голова.",
      context: "Боль: fare male",
      difficulty: 1,
      tags: ["health", "pain", "day-6"],
      level: "A1",
    },
    {
      id: "d6-4",
      it: "Vorrei fissare un appuntamento.",
      ru: "Я хотел бы записаться на приём.",
      context: "Запись к врачу",
      difficulty: 2,
      tags: ["health", "appointment", "day-6"],
      level: "A2",
    },
    {
      id: "d6-5",
      it: "Dov'è la farmacia più vicina?",
      ru: "Где находится ближайшая аптека?",
      context: "Аптека",
      difficulty: 2,
      tags: ["health", "pharmacy", "day-6"],
      level: "A2",
    },
    {
      id: "d6-6",
      it: "Devo prendere questa medicina tre volte al giorno.",
      ru: "Мне нужно принимать это лекарство три раза в день.",
      context: "Приём лекарств",
      difficulty: 3,
      tags: ["health", "medicine", "day-6"],
      level: "B1",
    },
    {
      id: "d6-7",
      it: "Quando posso tornare al lavoro?",
      ru: "Когда я могу вернуться к работе?",
      context: "Восстановление",
      difficulty: 2,
      tags: ["health", "recovery", "day-6"],
      level: "A2",
    },

    // ─── ДЕНЬ 7: Ресторан — бронь, заказ, рекомендации ───
    {
      id: "d7-1",
      it: "Ho una prenotazione per due persone.",
      ru: "У меня бронь на двух человек.",
      context: "Бронирование столика",
      difficulty: 2,
      tags: ["restaurant", "reservation", "day-7"],
      level: "A2",
    },
    {
      id: "d7-2",
      it: "Cosa consiglia come primo piatto?",
      ru: "Что вы рекомендуете в качестве первого блюда?",
      context: "Рекомендация блюда",
      difficulty: 2,
      tags: ["restaurant", "order", "day-7"],
      level: "A2",
    },
    {
      id: "d7-3",
      it: "Sono allergico ai frutti di mare.",
      ru: "У меня аллергия на морепродукты.",
      context: "Диетические ограничения",
      difficulty: 3,
      tags: ["restaurant", "allergy", "day-7"],
      level: "B1",
    },
    {
      id: "d7-4",
      it: "Il risotto ai funghi è ottimo.",
      ru: "Ризотто с грибами великолепно.",
      context: "Отзыв о блюде",
      difficulty: 2,
      tags: ["restaurant", "food", "day-7"],
      level: "A2",
    },
    {
      id: "d7-5",
      it: "Posso avere il conto, per favore?",
      ru: "Можно счёт, пожалуйста?",
      context: "Оплата в ресторане",
      difficulty: 1,
      tags: ["restaurant", "payment", "day-7"],
      level: "A1",
    },
    {
      id: "d7-6",
      it: "Il servizio è incluso?",
      ru: "Обслуживание включено?",
      context: "Чаевые",
      difficulty: 2,
      tags: ["restaurant", "payment", "day-7"],
      level: "A2",
    },
    {
      id: "d7-7",
      it: "È stata una cena eccellente!",
      ru: "Это был отличный ужин!",
      context: "Прощание в ресторане",
      difficulty: 2,
      tags: ["restaurant", "compliment", "day-7"],
      level: "A2",
    },

    // ─── ЭТАП 1: Я и моя жизнь — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s1_pron1",
      it: "Ciao, mi chiamo Andrii.",
      ru: "Привет, меня зовут Андрей.",
      context: "Произношение: chi",
      difficulty: 1,
      tags: ["stage-1", "pronunciation", "chi"],
      level: "A1",
    },
    {
      id: "s1_pron2",
      it: "Gli italiani parlano velocemente.",
      ru: "Итальянцы говорят быстро.",
      context: "Произношение: gli",
      difficulty: 2,
      tags: ["stage-1", "pronunciation", "gli"],
      level: "A2",
    },
    {
      id: "s1_pron3",
      it: "La famiglia è importante per me.",
      ru: "Семья важна для меня.",
      context: "Произношение: gli/famiglia",
      difficulty: 1,
      tags: ["stage-1", "pronunciation", "gli"],
      level: "A1",
    },

    // Блок 2: Личные фразы
    {
      id: "s1_pers1",
      it: "Sono uno sviluppatore web e lavoro con l'intelligenza artificiale.",
      ru: "Я веб-разработчик и работаю с искусственным интеллектом.",
      context: "О работе",
      difficulty: 2,
      tags: ["stage-1", "personal"],
      level: "A2",
    },
    {
      id: "s1_pers2",
      it: "Vivo a Lugano con mia moglie e i miei due figli.",
      ru: "Я живу в Лугано с женой и двумя детьми.",
      context: "О семье",
      difficulty: 2,
      tags: ["stage-1", "personal"],
      level: "A2",
    },
    {
      id: "s1_pers3",
      it: "Mi piace correre e nuotare.",
      ru: "Мне нравится бегать и плавать.",
      context: "О спорте",
      difficulty: 2,
      tags: ["stage-1", "personal"],
      level: "A2",
    },
    {
      id: "s1_pers4",
      it: "Sto cercando lavoro nel settore informatico.",
      ru: "Я ищу работу в IT-секторе.",
      context: "О поиске работы",
      difficulty: 2,
      tags: ["stage-1", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s1_a1_1",
      it: "Come ti chiami?",
      ru: "Как тебя зовут?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_2",
      it: "Di dove sei?",
      ru: "Откуда ты?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_3",
      it: "Quanti anni hai?",
      ru: "Сколько тебе лет?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_4",
      it: "Che lavoro fai?",
      ru: "Кем ты работаешь?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_5",
      it: "Hai figli?",
      ru: "У тебя есть дети?",
      context: "Семья",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_6",
      it: "Dove abiti?",
      ru: "Где ты живёшь?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },
    {
      id: "s1_a1_7",
      it: "Parli italiano?",
      ru: "Ты говоришь по-итальянски?",
      context: "Язык",
      difficulty: 1,
      tags: ["stage-1", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s1_a2_1",
      it: "Sono in Svizzera da due anni.",
      ru: "Я в Швейцарии уже два года.",
      context: "О себе",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_2",
      it: "Vengo dall'Ucraina, ma vivo a Lugano.",
      ru: "Я из Украины, но живу в Лугано.",
      context: "О себе",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_3",
      it: "I miei figli vanno a scuola qui.",
      ru: "Мои дети ходят в школу здесь.",
      context: "Семья",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_4",
      it: "Sto imparando l'italiano ogni giorno.",
      ru: "Я учу итальянский каждый день.",
      context: "Язык",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_5",
      it: "Mi piace molto vivere in Ticino.",
      ru: "Мне очень нравится жить в Тичино.",
      context: "О жизни",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_6",
      it: "Lavoro da casa e uso il computer tutto il giorno.",
      ru: "Я работаю из дома и использую компьютер весь день.",
      context: "О работе",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },
    {
      id: "s1_a2_7",
      it: "Nel tempo libero faccio sport e cammino lungo il lago.",
      ru: "В свободное время занимаюсь спортом и гуляю вдоль озера.",
      context: "Досуг",
      difficulty: 2,
      tags: ["stage-1", "a2"],
      level: "A2",
    },

    // Блок 5: Повторение
    {
      id: "s1_rev1",
      it: "Piacere di conoscerti, sono Andrii.",
      ru: "Приятно познакомиться, я Андрей.",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-1", "review"],
      level: "A1",
    },
    {
      id: "s1_rev2",
      it: "Abito in Svizzera, ma sono ucraino.",
      ru: "Я живу в Швейцарии, но я украинец.",
      context: "О себе",
      difficulty: 2,
      tags: ["stage-1", "review"],
      level: "A2",
    },
    {
      id: "s1_rev3",
      it: "Ho due figli e una moglie meravigliosa.",
      ru: "У меня двое детей и замечательная жена.",
      context: "Семья",
      difficulty: 2,
      tags: ["stage-1", "review"],
      level: "A2",
    },

    // ─── ЭТАП 2: Кафе и ресторан — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s2_pron1",
      it: "Vorrei un cappuccino, per favore.",
      ru: "Я бы хотел капучино, пожалуйста.",
      context: "Произношение: doppia c",
      difficulty: 1,
      tags: ["stage-2", "pronunciation"],
      level: "A1",
    },
    {
      id: "s2_pron2",
      it: "Il cornetto è buonissimo qui.",
      ru: "Здесь круассан очень вкусный.",
      context: "Произношение: doppia n",
      difficulty: 1,
      tags: ["stage-2", "pronunciation"],
      level: "A1",
    },
    {
      id: "s2_pron3",
      it: "Scusi, dov'è la cassa?",
      ru: "Извините, где касса?",
      context: "Произношение: sc",
      difficulty: 1,
      tags: ["stage-2", "pronunciation"],
      level: "A1",
    },

    // Блок 2: Личные фразы
    {
      id: "s2_pers1",
      it: "Ogni mattina bevo un caffè al bar vicino a casa.",
      ru: "Каждое утро я пью кофе в баре рядом с домом.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-2", "personal"],
      level: "A2",
    },
    {
      id: "s2_pers2",
      it: "Di solito prendo un cappuccino e un cornetto.",
      ru: "Обычно я беру капучино и круассан.",
      context: "Личное",
      difficulty: 1,
      tags: ["stage-2", "personal"],
      level: "A1",
    },
    {
      id: "s2_pers3",
      it: "A volte porto i bambini al bar il sabato mattina.",
      ru: "Иногда я вожу детей в бар в субботу утром.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-2", "personal"],
      level: "A2",
    },
    {
      id: "s2_pers4",
      it: "Mi piace sedermi fuori quando c'è il sole.",
      ru: "Мне нравится сидеть на улице когда светит солнце.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-2", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s2_a1_1",
      it: "Un caffè, per favore.",
      ru: "Один кофе, пожалуйста.",
      context: "Заказ",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_2",
      it: "Quant'è?",
      ru: "Сколько стоит?",
      context: "Оплата",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_3",
      it: "Il conto, per favore.",
      ru: "Счёт, пожалуйста.",
      context: "Оплата",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_4",
      it: "Posso avere il menu?",
      ru: "Можно мне меню?",
      context: "Просьба",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_5",
      it: "Pago con la carta.",
      ru: "Плачу картой.",
      context: "Оплата",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_6",
      it: "Grazie, arrivederci!",
      ru: "Спасибо, до свидания!",
      context: "Прощание",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },
    {
      id: "s2_a1_7",
      it: "È libero questo tavolo?",
      ru: "Этот столик свободен?",
      context: "В ресторане",
      difficulty: 1,
      tags: ["stage-2", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s2_a2_1",
      it: "Vorrei prenotare un tavolo per due persone.",
      ru: "Я хотел бы забронировать столик на двух человек.",
      context: "Бронирование",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_2",
      it: "Cosa consiglia oggi?",
      ru: "Что вы рекомендуете сегодня?",
      context: "Рекомендация",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_3",
      it: "C'è qualcosa senza glutine?",
      ru: "Есть что-нибудь без глютена?",
      context: "Диета",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_4",
      it: "Possiamo sederci fuori?",
      ru: "Мы можем сесть на улице?",
      context: "Место",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_5",
      it: "Il servizio è incluso nel conto?",
      ru: "Обслуживание включено в счёт?",
      context: "Оплата",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_6",
      it: "Quanto si aspetta per un tavolo?",
      ru: "Сколько ждать столика?",
      context: "Ожидание",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },
    {
      id: "s2_a2_7",
      it: "Potrei avere un bicchiere d'acqua?",
      ru: "Можно мне стакан воды?",
      context: "Просьба",
      difficulty: 2,
      tags: ["stage-2", "a2"],
      level: "A2",
    },

    // Блок 5: Повторение из Этапа 1
    {
      id: "s2_rev1",
      it: "Mi chiamo Andrii, sono ucraino.",
      ru: "Меня зовут Андрей, я украинец.",
      context: "Повторение: знакомство",
      difficulty: 1,
      tags: ["stage-2", "review"],
      level: "A1",
    },
    {
      id: "s2_rev2",
      it: "Vivo a Lugano da due anni.",
      ru: "Я живу в Лугано уже два года.",
      context: "Повторение: о себе",
      difficulty: 2,
      tags: ["stage-2", "review"],
      level: "A2",
    },
    {
      id: "s2_rev3",
      it: "Ho due figli.",
      ru: "У меня двое детей.",
      context: "Повторение: семья",
      difficulty: 1,
      tags: ["stage-2", "review"],
      level: "A1",
    },

    // ─── ЭТАП 3: Магазин и рынок — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s3_pron1",
      it: "Scusi, dov'è la cassa?",
      ru: "Извините, где касса?",
      context: "Произношение: sc",
      difficulty: 1,
      tags: ["stage-3", "pronunciation"],
      level: "A1",
    },
    {
      id: "s3_pron2",
      it: "Cerco delle scarpe da corsa.",
      ru: "Я ищу кроссовки.",
      context: "Произношение: ce/sce",
      difficulty: 1,
      tags: ["stage-3", "pronunciation"],
      level: "A1",
    },
    {
      id: "s3_pron3",
      it: "Gli sconti iniziano domani.",
      ru: "Скидки начинаются завтра.",
      context: "Произношение: gli",
      difficulty: 2,
      tags: ["stage-3", "pronunciation"],
      level: "A2",
    },

    // Блок 2: Личные фразы
    {
      id: "s3_pers1",
      it: "Vado al supermercato quasi ogni giorno.",
      ru: "Я хожу в супермаркет почти каждый день.",
      context: "Личное",
      difficulty: 1,
      tags: ["stage-3", "personal"],
      level: "A1",
    },
    {
      id: "s3_pers2",
      it: "Compro frutta e verdura al mercato del sabato.",
      ru: "Я покупаю фрукты и овощи на субботнем рынке.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-3", "personal"],
      level: "A2",
    },
    {
      id: "s3_pers3",
      it: "Ho bisogno di un costume da bagno per la piscina.",
      ru: "Мне нужен купальный костюм для бассейна.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-3", "personal"],
      level: "A2",
    },
    {
      id: "s3_pers4",
      it: "I bambini crescono in fretta, compro spesso nuovi vestiti.",
      ru: "Дети быстро растут, я часто покупаю новую одежду.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-3", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s3_a1_1",
      it: "Quanto costa questo?",
      ru: "Сколько это стоит?",
      context: "Цена",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_2",
      it: "Cerco del pane fresco.",
      ru: "Я ищу свежий хлеб.",
      context: "Поиск товара",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_3",
      it: "Mi serve anche del latte.",
      ru: "Мне нужно ещё молоко.",
      context: "Покупка",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_4",
      it: "Posso avere un sacchetto?",
      ru: "Можно пакет?",
      context: "Упаковка",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_5",
      it: "Pago con la carta.",
      ru: "Плачу картой.",
      context: "Оплата",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_6",
      it: "Dov'è il reparto frutta?",
      ru: "Где отдел с фруктами?",
      context: "Навигация",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },
    {
      id: "s3_a1_7",
      it: "Avete questo in taglia media?",
      ru: "У вас есть это в среднем размере?",
      context: "Размер",
      difficulty: 1,
      tags: ["stage-3", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s3_a2_1",
      it: "Vorrei un chilo di pomodori, per favore.",
      ru: "Я хотел бы килограмм помидоров, пожалуйста.",
      context: "Количество",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_2",
      it: "È troppo caro per me, c'è qualcosa di meno costoso?",
      ru: "Это слишком дорого, есть что-нибудь подешевле?",
      context: "Цена",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_3",
      it: "Avete latte di soia o latte di avena?",
      ru: "У вас есть соевое молоко или овсяное молоко?",
      context: "Альтернативы",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_4",
      it: "Questo è in offerta questa settimana?",
      ru: "Это на акции на этой неделе?",
      context: "Скидки",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_5",
      it: "Posso cambiare questo se non va bene?",
      ru: "Могу ли я это обменять если не подойдёт?",
      context: "Возврат",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_6",
      it: "Dove posso trovare i prodotti biologici?",
      ru: "Где я могу найти органические продукты?",
      context: "Навигация",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },
    {
      id: "s3_a2_7",
      it: "Quanto tempo ci vuole per la consegna a domicilio?",
      ru: "Сколько времени занимает доставка на дом?",
      context: "Доставка",
      difficulty: 2,
      tags: ["stage-3", "a2"],
      level: "A2",
    },

    // Блок 5: Повторение из Этапов 1-2
    {
      id: "s3_rev1",
      it: "Vivo a Lugano con la mia famiglia.",
      ru: "Я живу в Лугано с семьёй.",
      context: "Повторение: о себе",
      difficulty: 1,
      tags: ["stage-3", "review"],
      level: "A1",
    },
    {
      id: "s3_rev2",
      it: "Di solito prendo un caffè al mattino.",
      ru: "Обычно я пью кофе утром.",
      context: "Повторение: кафе",
      difficulty: 1,
      tags: ["stage-3", "review"],
      level: "A1",
    },
    {
      id: "s3_rev3",
      it: "Ho due figli che vanno a scuola.",
      ru: "У меня двое детей которые ходят в школу.",
      context: "Повторение: семья",
      difficulty: 2,
      tags: ["stage-3", "review"],
      level: "A2",
    },

    // ─── ЭТАП 4: Работа и технологии — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s4_pron1",
      it: "Lavoro con l'intelligenza artificiale.",
      ru: "Я работаю с искусственным интеллектом.",
      context: "Произношение: gli",
      difficulty: 1,
      tags: ["stage-4", "pronunciation"],
      level: "A1",
    },
    {
      id: "s4_pron2",
      it: "Ho una videochiamata con il cliente.",
      ru: "У меня видеозвонок с клиентом.",
      context: "Произношение: chi",
      difficulty: 2,
      tags: ["stage-4", "pronunciation"],
      level: "A2",
    },
    {
      id: "s4_pron3",
      it: "Il progetto è quasi finito.",
      ru: "Проект почти завершён.",
      context: "Произношение: ge",
      difficulty: 2,
      tags: ["stage-4", "pronunciation"],
      level: "A2",
    },

    // Блок 2: Личные фразы
    {
      id: "s4_pers1",
      it: "Lavoro come sviluppatore freelance da casa.",
      ru: "Я работаю как фриланс-разработчик из дома.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-4", "personal"],
      level: "A2",
    },
    {
      id: "s4_pers2",
      it: "Creo siti web e applicazioni per i clienti.",
      ru: "Я создаю сайты и приложения для клиентов.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-4", "personal"],
      level: "A2",
    },
    {
      id: "s4_pers3",
      it: "Sto cercando un lavoro fisso nel settore informatico in Ticino.",
      ru: "Я ищу постоянную работу в IT-секторе в Тичино.",
      context: "Личное",
      difficulty: 3,
      tags: ["stage-4", "personal"],
      level: "B1",
    },
    {
      id: "s4_pers4",
      it: "Mi occupo di sviluppo web e intelligenza artificiale.",
      ru: "Я занимаюсь веб-разработкой и искусственным интеллектом.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-4", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s4_a1_1",
      it: "Che lavoro fai?",
      ru: "Кем ты работаешь?",
      context: "Знакомство",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_2",
      it: "Lavoro da casa.",
      ru: "Я работаю из дома.",
      context: "О работе",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_3",
      it: "Ho una riunione alle tre.",
      ru: "У меня встреча в три.",
      context: "Расписание",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_4",
      it: "Mando una email adesso.",
      ru: "Я сейчас отправляю письмо.",
      context: "Задача",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_5",
      it: "Il progetto è pronto.",
      ru: "Проект готов.",
      context: "Завершение",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_6",
      it: "Lavoro con il computer tutto il giorno.",
      ru: "Я работаю за компьютером весь день.",
      context: "О работе",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },
    {
      id: "s4_a1_7",
      it: "Sono libero domani pomeriggio.",
      ru: "Я свободен завтра днём.",
      context: "Расписание",
      difficulty: 1,
      tags: ["stage-4", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s4_a2_1",
      it: "Possiamo fissare una chiamata per domani?",
      ru: "Можем ли мы назначить звонок на завтра?",
      context: "Организация",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_2",
      it: "Ti mando i file entro oggi.",
      ru: "Я пришлю тебе файлы к сегодняшнему дню.",
      context: "Дедлайн",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_3",
      it: "Stiamo lavorando su un nuovo progetto.",
      ru: "Мы работаем над новым проектом.",
      context: "Текущая задача",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_4",
      it: "Hai ricevuto la mia email?",
      ru: "Ты получил моё письмо?",
      context: "Коммуникация",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_5",
      it: "Posso avere più tempo per completare il lavoro?",
      ru: "Могу ли я получить больше времени для завершения работы?",
      context: "Дедлайн",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_6",
      it: "Lavoro con clienti in tutta Europa.",
      ru: "Я работаю с клиентами по всей Европе.",
      context: "О работе",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },
    {
      id: "s4_a2_7",
      it: "Preferisco lavorare in modo autonomo.",
      ru: "Я предпочитаю работать самостоятельно.",
      context: "О себе",
      difficulty: 2,
      tags: ["stage-4", "a2"],
      level: "A2",
    },

    // Блок 5: Повторение из Этапов 1-3
    {
      id: "s4_rev1",
      it: "Vivo a Lugano con mia moglie e i miei due figli.",
      ru: "Я живу в Лугано с женой и двумя детьми.",
      context: "Повторение: семья",
      difficulty: 2,
      tags: ["stage-4", "review"],
      level: "A2",
    },
    {
      id: "s4_rev2",
      it: "Di solito prendo un caffè prima di iniziare a lavorare.",
      ru: "Обычно я пью кофе перед началом работы.",
      context: "Повторение: кафе + работа",
      difficulty: 2,
      tags: ["stage-4", "review"],
      level: "A2",
    },
    {
      id: "s4_rev3",
      it: "Faccio la spesa il sabato mattina con i bambini.",
      ru: "Я делаю покупки в субботу утром с детьми.",
      context: "Повторение: магазин",
      difficulty: 2,
      tags: ["stage-4", "review"],
      level: "A2",
    },

    // ─── ЭТАП 5: Транспорт и город — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s5_pron1",
      it: "Scusi, dov'è la stazione?",
      ru: "Извините, где вокзал?",
      context: "Произношение: sc",
      difficulty: 1,
      tags: ["stage-5", "pronunciation"],
      level: "A1",
    },
    {
      id: "s5_pron2",
      it: "Questo autobus va in centro?",
      ru: "Этот автобус едет в центр?",
      context: "Произношение: ce",
      difficulty: 1,
      tags: ["stage-5", "pronunciation"],
      level: "A1",
    },
    {
      id: "s5_pron3",
      it: "Gli orari cambiano il fine settimana.",
      ru: "Расписание меняется в выходные.",
      context: "Произношение: gli",
      difficulty: 2,
      tags: ["stage-5", "pronunciation"],
      level: "A2",
    },

    // Блок 2: Личные фразы
    {
      id: "s5_pers1",
      it: "Di solito vado in macchina, ma a volte prendo il treno.",
      ru: "Обычно я езжу на машине, но иногда беру поезд.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-5", "personal"],
      level: "A2",
    },
    {
      id: "s5_pers2",
      it: "La stazione di Lugano è vicino al lago.",
      ru: "Вокзал Лугано находится рядом с озером.",
      context: "Личное",
      difficulty: 1,
      tags: ["stage-5", "personal"],
      level: "A1",
    },
    {
      id: "s5_pers3",
      it: "Dove posso parcheggiare in centro a Lugano?",
      ru: "Где можно припарковаться в центре Лугано?",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-5", "personal"],
      level: "A2",
    },
    {
      id: "s5_pers4",
      it: "Porto i bambini a scuola in macchina ogni mattina.",
      ru: "Каждое утро я везу детей в школу на машине.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-5", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s5_a1_1",
      it: "Dov'è la fermata dell'autobus?",
      ru: "Где остановка автобуса?",
      context: "Транспорт",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_2",
      it: "Quanto costa il biglietto?",
      ru: "Сколько стоит билет?",
      context: "Транспорт",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_3",
      it: "A che ora parte il prossimo treno?",
      ru: "В котором часу отходит следующий поезд?",
      context: "Расписание",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_4",
      it: "Devo scendere alla prossima fermata.",
      ru: "Мне нужно выйти на следующей остановке.",
      context: "Транспорт",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_5",
      it: "Giro a destra o a sinistra?",
      ru: "Мне повернуть направо или налево?",
      context: "Навигация",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_6",
      it: "È lontano da qui?",
      ru: "Это далеко отсюда?",
      context: "Навигация",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },
    {
      id: "s5_a1_7",
      it: "Quanto tempo ci vuole?",
      ru: "Сколько времени займёт?",
      context: "Время",
      difficulty: 1,
      tags: ["stage-5", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s5_a2_1",
      it: "C'è un parcheggio gratuito vicino al centro?",
      ru: "Есть ли бесплатная парковка рядом с центром?",
      context: "Парковка",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_2",
      it: "Quanto costa l'abbonamento mensile SBB?",
      ru: "Сколько стоит месячный абонемент SBB?",
      context: "Абонемент",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_3",
      it: "Il treno è in ritardo di dieci minuti.",
      ru: "Поезд опаздывает на десять минут.",
      context: "Опоздание",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_4",
      it: "Devo cambiare treno a Bellinzona.",
      ru: "Мне нужно пересесть в Беллинцоне.",
      context: "Пересадка",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_5",
      it: "Posso comprare il biglietto sull'app delle FFS?",
      ru: "Могу ли я купить билет в приложении SBB?",
      context: "Билеты",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_6",
      it: "Quale linea devo prendere per andare a Paradiso?",
      ru: "На какой маршрут мне сесть чтобы добраться до Парадизо?",
      context: "Маршрут",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },
    {
      id: "s5_a2_7",
      it: "C'è traffico in centro a quest'ora.",
      ru: "В центре в это время пробки.",
      context: "Трафик",
      difficulty: 2,
      tags: ["stage-5", "a2"],
      level: "A2",
    },

    // Блок 5: Повторение из Этапов 1-4
    {
      id: "s5_rev1",
      it: "Dopo il lavoro vado a fare la spesa.",
      ru: "После работы я иду за покупками.",
      context: "Повторение: работа + магазин",
      difficulty: 2,
      tags: ["stage-5", "review"],
      level: "A2",
    },
    {
      id: "s5_rev2",
      it: "Prendo un caffè prima di prendere il treno.",
      ru: "Я выпиваю кофе перед тем как сесть на поезд.",
      context: "Повторение: кафе + транспорт",
      difficulty: 2,
      tags: ["stage-5", "review"],
      level: "A2",
    },
    {
      id: "s5_rev3",
      it: "I miei figli vengono a scuola con me in macchina.",
      ru: "Мои дети едут в школу со мной на машине.",
      context: "Повторение: семья + транспорт",
      difficulty: 2,
      tags: ["stage-5", "review"],
      level: "A2",
    },

    // ─── ЭТАП 6: Врач и здоровье — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s6_pron1",
      it: "Ho bisogno di un medico.",
      ru: "Мне нужен врач.",
      context: "Произношение: bisogno/gn",
      difficulty: 1,
      tags: ["stage-6", "pronunciation"],
      level: "A1",
    },
    {
      id: "s6_pron2",
      it: "La farmacia è chiusa adesso.",
      ru: "Аптека сейчас закрыта.",
      context: "Произношение: chi",
      difficulty: 1,
      tags: ["stage-6", "pronunciation"],
      level: "A1",
    },
    {
      id: "s6_pron3",
      it: "Gli esami del sangue sono pronti.",
      ru: "Анализы крови готовы.",
      context: "Произношение: gli",
      difficulty: 2,
      tags: ["stage-6", "pronunciation"],
      level: "A2",
    },

    // Блок 2: Личные фразы
    {
      id: "s6_pers1",
      it: "Mio figlio ha la febbre da ieri sera.",
      ru: "У моего сына температура с вчерашнего вечера.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-6", "personal"],
      level: "A2",
    },
    {
      id: "s6_pers2",
      it: "Devo portare i bambini dal pediatra.",
      ru: "Мне нужно отвести детей к педиатру.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-6", "personal"],
      level: "A2",
    },
    {
      id: "s6_pers3",
      it: "Ho mal di schiena dopo la corsa.",
      ru: "У меня болит спина после пробежки.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-6", "personal"],
      level: "A2",
    },
    {
      id: "s6_pers4",
      it: "La nostra cassa malati è la CSS.",
      ru: "Наша страховая касса — CSS.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-6", "personal"],
      level: "A2",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s6_a1_1",
      it: "Non mi sento bene.",
      ru: "Я плохо себя чувствую.",
      context: "Самочувствие",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_2",
      it: "Ho mal di testa.",
      ru: "У меня болит голова.",
      context: "Симптом",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_3",
      it: "Ho la febbre.",
      ru: "У меня температура.",
      context: "Симптом",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_4",
      it: "Ho bisogno di un medico.",
      ru: "Мне нужен врач.",
      context: "Помощь",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_5",
      it: "Dov'è la farmacia più vicina?",
      ru: "Где ближайшая аптека?",
      context: "Навигация",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_6",
      it: "Ho un appuntamento alle dieci.",
      ru: "У меня приём в десять.",
      context: "Запись",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },
    {
      id: "s6_a1_7",
      it: "Mi fa male qui.",
      ru: "У меня болит здесь.",
      context: "Боль",
      difficulty: 1,
      tags: ["stage-6", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2
    {
      id: "s6_a2_1",
      it: "Vorrei fissare un appuntamento con il medico.",
      ru: "Я хотел бы записаться на приём к врачу.",
      context: "Запись",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_2",
      it: "Ho la febbre da due giorni e mi sento molto stanco.",
      ru: "У меня температура уже два дня и я очень устал.",
      context: "Симптомы",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_3",
      it: "Sono allergico alla penicillina.",
      ru: "У меня аллергия на пенициллин.",
      context: "Аллергия",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_4",
      it: "Devo prendere questa medicina tre volte al giorno.",
      ru: "Мне нужно принимать это лекарство три раза в день.",
      context: "Лечение",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_5",
      it: "Ho bisogno di una ricetta medica.",
      ru: "Мне нужен рецепт врача.",
      context: "Рецепт",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_6",
      it: "Quando posso tornare al lavoro?",
      ru: "Когда я могу вернуться к работе?",
      context: "Восстановление",
      difficulty: 2,
      tags: ["stage-6", "a2"],
      level: "A2",
    },
    {
      id: "s6_a2_7",
      it: "Come funziona il sistema sanitario in Svizzera?",
      ru: "Как работает система здравоохранения в Швейцарии?",
      context: "Система",
      difficulty: 3,
      tags: ["stage-6", "a2"],
      level: "B1",
    },

    // Блок 5: Повторение из Этапов 1-5
    {
      id: "s6_rev1",
      it: "Dopo la corsa mi fermo al bar per un caffè.",
      ru: "После пробежки я захожу в бар за кофе.",
      context: "Повторение: спорт + кафе",
      difficulty: 2,
      tags: ["stage-6", "review"],
      level: "A2",
    },
    {
      id: "s6_rev2",
      it: "Prendo la macchina per portare mio figlio dal dottore.",
      ru: "Я беру машину чтобы отвезти сына к врачу.",
      context: "Повторение: транспорт + здоровье",
      difficulty: 2,
      tags: ["stage-6", "review"],
      level: "A2",
    },
    {
      id: "s6_rev3",
      it: "In farmacia compro anche vitamine per i bambini.",
      ru: "В аптеке я также покупаю витамины для детей.",
      context: "Повторение: магазин + здоровье",
      difficulty: 2,
      tags: ["stage-6", "review"],
      level: "A2",
    },

    // ─── ЭТАП 7: Аптека и страховка — полный набор 24 фразы ───

    // Блок 1: Произношение
    {
      id: "s7_pron1",
      it: "Cerco qualcosa per il mal di gola.",
      ru: "Я ищу что-нибудь от боли в горле.",
      context: "Произношение: ce/ge",
      difficulty: 1,
      tags: ["stage-7", "pronunciation"],
      level: "A1",
    },
    {
      id: "s7_pron2",
      it: "Gli sciroppi sono nello scaffale in fondo.",
      ru: "Сиропы на полке в конце.",
      context: "Произношение: gli/sci",
      difficulty: 2,
      tags: ["stage-7", "pronunciation"],
      level: "A2",
    },
    {
      id: "s7_pron3",
      it: "Prenda queste compresse tre volte al giorno.",
      ru: "Принимайте эти таблетки три раза в день.",
      context: "Произношение: pr/comp",
      difficulty: 2,
      tags: ["stage-7", "pronunciation"],
      level: "A2",
    },

    // Блок 2: Личные фразы
    {
      id: "s7_pers1",
      it: "La nostra franchigia è di trecento franchi.",
      ru: "Наша франшиза составляет триста франков.",
      context: "Личное",
      difficulty: 3,
      tags: ["stage-7", "personal"],
      level: "B1",
    },
    {
      id: "s7_pers2",
      it: "Ogni anno cambio la cassa malati per risparmiare.",
      ru: "Каждый год я меняю страховую кассу чтобы сэкономить.",
      context: "Личное",
      difficulty: 3,
      tags: ["stage-7", "personal"],
      level: "B1",
    },
    {
      id: "s7_pers3",
      it: "Compro le medicine per i bambini sempre in farmacia.",
      ru: "Я всегда покупаю лекарства для детей в аптеке.",
      context: "Личное",
      difficulty: 2,
      tags: ["stage-7", "personal"],
      level: "A2",
    },
    {
      id: "s7_pers4",
      it: "Devo inviare la fattura alla mia assicurazione entro trenta giorni.",
      ru: "Я должен отправить счёт в свою страховку в течение тридцати дней.",
      context: "Личное",
      difficulty: 3,
      tags: ["stage-7", "personal"],
      level: "B1",
    },

    // Блок 3: Базовые конструкции A1
    {
      id: "s7_a1_1",
      it: "Cerco qualcosa per il mal di testa.",
      ru: "Я ищу что-нибудь от головной боли.",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_2",
      it: "Ho bisogno di cerotti.",
      ru: "Мне нужны пластыри.",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_3",
      it: "Avete questo senza ricetta?",
      ru: "У вас есть это без рецепта?",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_4",
      it: "Quanto costa questo medicinale?",
      ru: "Сколько стоит это лекарство?",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_5",
      it: "Ho la ricetta del medico.",
      ru: "У меня есть рецепт врача.",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_6",
      it: "Mio figlio ha bisogno di sciroppo per la tosse.",
      ru: "Моему сыну нужен сироп от кашля.",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },
    {
      id: "s7_a1_7",
      it: "A che ora apre la farmacia?",
      ru: "В котором часу открывается аптека?",
      context: "Аптека",
      difficulty: 1,
      tags: ["stage-7", "a1"],
      level: "A1",
    },

    // Блок 4: Расширенные фразы A2/B1
    {
      id: "s7_a2_1",
      it: "Come funziona la cassa malati in Svizzera?",
      ru: "Как работает страховая касса в Швейцарии?",
      context: "Страховка",
      difficulty: 2,
      tags: ["stage-7", "a2"],
      level: "A2",
    },
    {
      id: "s7_a2_2",
      it: "Qual è la differenza tra assicurazione base e complementare?",
      ru: "В чём разница между базовой и дополнительной страховкой?",
      context: "Страховка",
      difficulty: 3,
      tags: ["stage-7", "a2"],
      level: "B1",
    },
    {
      id: "s7_a2_3",
      it: "Devo pagare la franchigia prima che la cassa rimborsi.",
      ru: "Я должен заплатить франшизу прежде чем касса возместит расходы.",
      context: "Страховка",
      difficulty: 3,
      tags: ["stage-7", "a2"],
      level: "B1",
    },
    {
      id: "s7_a2_4",
      it: "Posso cambiare la cassa malati entro il 30 novembre.",
      ru: "Я могу сменить страховую кассу до 30 ноября.",
      context: "Страховка",
      difficulty: 2,
      tags: ["stage-7", "a2"],
      level: "A2",
    },
    {
      id: "s7_a2_5",
      it: "Ho bisogno di un certificato medico per l'assicurazione.",
      ru: "Мне нужна медицинская справка для страховки.",
      context: "Документы",
      difficulty: 2,
      tags: ["stage-7", "a2"],
      level: "A2",
    },
    {
      id: "s7_a2_6",
      it: "Posso rimborsare le medicine con la cassa complementare?",
      ru: "Могу ли я возместить лекарства через дополнительную страховку?",
      context: "Страховка",
      difficulty: 3,
      tags: ["stage-7", "a2"],
      level: "B1",
    },
    {
      id: "s7_a2_7",
      it: "Il medico di base deve fare una richiesta per lo specialista.",
      ru: "Семейный врач должен сделать направление к специалисту.",
      context: "Система",
      difficulty: 3,
      tags: ["stage-7", "a2"],
      level: "B1",
    },

    // Блок 5: Повторение из Этапов 1-6
    {
      id: "s7_rev1",
      it: "Dopo la visita medica vado in farmacia.",
      ru: "После визита к врачу я иду в аптеку.",
      context: "Повторение: здоровье + аптека",
      difficulty: 2,
      tags: ["stage-7", "review"],
      level: "A2",
    },
    {
      id: "s7_rev2",
      it: "Prendo la macchina per andare in farmacia con i bambini.",
      ru: "Я беру машину чтобы поехать в аптеку с детьми.",
      context: "Повторение: транспорт + аптека",
      difficulty: 2,
      tags: ["stage-7", "review"],
      level: "A2",
    },
    {
      id: "s7_rev3",
      it: "In Svizzera la sanità è buona ma cara.",
      ru: "В Швейцарии здравоохранение хорошее но дорогое.",
      context: "Повторение: жизнь в Швейцарии",
      difficulty: 2,
      tags: ["stage-7", "review"],
      level: "A2",
    },

    // ─── ДЕНЬ 0: базовые личные фразы (резерв) ───
    {
      id: "p1",
      it: "Sono uno sviluppatore.",
      ru: "Я разработчик.",
      context: "О себе",
      difficulty: 1,
      tags: ["self-intro", "work", "day-0"],
      level: "A1",
    },
    {
      id: "p2",
      it: "Lavoro con l'intelligenza artificiale.",
      ru: "Я работаю с искусственным интеллектом.",
      context: "О работе",
      difficulty: 2,
      tags: ["work", "day-0"],
      level: "A2",
    },
    {
      id: "p3",
      it: "Vivo a Lugano con la mia famiglia.",
      ru: "Я живу в Лугано с семьёй.",
      context: "О себе",
      difficulty: 1,
      tags: ["self-intro", "daily", "day-0"],
      level: "A1",
    },
    {
      id: "p4",
      it: "Sto imparando l'italiano.",
      ru: "Я учу итальянский.",
      context: "О себе",
      difficulty: 1,
      tags: ["self-intro", "day-0"],
      level: "A1",
    },
  ],
};
